#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")";

function dotfiles() {
	dir=~/.dotfiles
	files=".bashrc .bash_profile .vimrc .vim .gitconfig .gitignore .nvm/default-packages"

	for file in $files; do
		touch ~/$file # create if doesn't exist
		rm -r ~/$file # remove old version
    echo "Creating symlink to $file..."
    ln -s $dir/$file ~/$file # make new symlink
	done

	echo "Creating symlink to VS Code Settings..."
	rm ~/Library/Application\ Support/Code/User/settings.json
	ln -s $dir/.vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json

	touch ~/.hushlogin
	source ~/.bash_profile;

	echo "Done. Bye."
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	dotfiles;
else
	read -p "This will overwrite existing files. Are you sure? (y/n) " -n 1;
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		dotfiles;
	fi;
fi;
unset dotfiles;
